version: '3.3'
services:
  backend:
    image: bizhop17/project234-backend:latest
    ports:
      - "7072:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "7071:80"
    volumes:
      - type: bind
        source: ./xxx
        target: /setting